apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    konvoy.d2iq.io/cluster-name: {{ .Values.cluster.name }}
    konvoy.d2iq.io/cni: calico
    konvoy.d2iq.io/cosi-controller: ""
    konvoy.d2iq.io/csi: local-volume-provisioner
    konvoy.d2iq.io/loadbalancer: metallb
    konvoy.d2iq.io/provider: preprovisioned
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.cluster.network.podCIDR }}
    services:
      cidrBlocks:
      - {{ .Values.cluster.network.serviceCIDR }}
  controlPlaneEndpoint:
    host: {{ .Values.cluster.controlPlaneEndpoint.host | quote }}
    port: {{ .Values.cluster.controlPlaneEndpoint.port }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Values.cluster.name }}-control-plane
    namespace: {{ .Values.cluster.namespace }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
    kind: PreprovisionedCluster
    name: {{ .Values.cluster.name }}
    namespace: {{ .Values.cluster.namespace }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          audit-log-maxage: "30"
          audit-log-maxbackup: "10"
          audit-log-maxsize: "100"
          audit-log-path: /var/log/audit/kube-apiserver-audit.log
          audit-policy-file: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml
          encryption-provider-config: /etc/kubernetes/pki/encryption-config.yaml
        extraVolumes:
        - hostPath: /etc/kubernetes/audit-policy/
          mountPath: /etc/kubernetes/audit-policy/
          name: audit-policy
        - hostPath: /var/log/kubernetes/audit
          mountPath: /var/log/audit/
          name: audit-logs
      controllerManager:
        extraArgs:
          cloud-provider: ""
      dns: {}
      etcd: {}
      networking: {}
      scheduler: {}
    files:
    - content: |
        #!/bin/bash
        set -euo pipefail
        IFS=$'\n\t'

        SCRIPT_NAME="$(basename "${0}")"
        readonly SCRIPT_NAME

        declare -r KUBEADM_INIT_FILE="/run/kubeadm/kubeadm.yaml"
        declare -r KUBEADM_INIT_FILE_FLATCAR="/etc/kubeadm.yml"
        declare -r KUBEADM_INIT_TMP_FILE_FLATCAR="/tmp/kubeadm.yml"
        declare -r KUBE_VIP_MANIFEST_FILE="/etc/kubernetes/manifests/kube-vip.yaml"

        function use_super_admin_conf {
          if [[ (-f ${KUBEADM_INIT_FILE} || -f ${KUBEADM_INIT_FILE_FLATCAR}) && -f ${KUBE_VIP_MANIFEST_FILE} ]]; then
            sed -i 's#path: /etc/kubernetes/admin.conf#path: /etc/kubernetes/super-admin.conf#' \
              /etc/kubernetes/manifests/kube-vip.yaml
          fi
        }

        function use_admin_conf() {
          if [[ (-f ${KUBEADM_INIT_FILE} || -f ${KUBEADM_INIT_FILE_FLATCAR} || -f ${KUBEADM_INIT_TMP_FILE_FLATCAR}) && -f ${KUBE_VIP_MANIFEST_FILE} ]]; then
            sed -i 's#path: /etc/kubernetes/super-admin.conf#path: /etc/kubernetes/admin.conf#' \
              /etc/kubernetes/manifests/kube-vip.yaml
          fi
        }

        function print_usage {
          cat >&2 <<EOF
        Configures the kube-vip Static Pod, and restarts kube-vip,
        because a configuration change causes kubelet to delete and re-create a Static Pod.
        Usage: ${SCRIPT_NAME} [use-super-admin.conf|use-admin.conf]
        EOF
        }

        function run_cmd() {
          while [ -n "$1" ]; do
            case $1 in
            use-super-admin.conf)
              use_super_admin_conf
              break
              ;;
            use-admin.conf)
              use_admin_conf
              break
              ;;
            -h | --help)
              print_usage
              exit
              ;;
            *)
              echo "invalid argument"
              exit 1
              ;;
            esac
            shift
          done
        }

        run_cmd "$@"
      path: /etc/konvoy/configure-kube-vip.sh
      permissions: "0700"
    - content: |
        # Taken from https://github.com/kubernetes/kubernetes/blob/v1.34.3/cluster/gce/gci/configure-helper.sh#L1144
        # Recommended in Kubernetes docs
        apiVersion: audit.k8s.io/v1
        kind: Policy
        rules:
          # The following requests were manually identified as high-volume and low-risk,
          # so drop them.
          - level: None
            users: ["system:kube-proxy"]
            verbs: ["watch"]
            resources:
              - group: "" # core
                resources: ["endpoints", "services", "services/status"]
          - level: None
            # Ingress controller reads 'configmaps/ingress-uid' through the unsecured port.
            # TODO(#46983): Change this to the ingress controller service account.
            users: ["system:unsecured"]
            namespaces: ["kube-system"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["configmaps"]
          - level: None
            users: ["kubelet"] # legacy kubelet identity
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            userGroups: ["system:nodes"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["nodes", "nodes/status"]
          - level: None
            users:
              - system:kube-controller-manager
              - system:cloud-controller-manager
              - system:kube-scheduler
              - system:serviceaccount:kube-system:endpoint-controller
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["endpoints"]
          - level: None
            users: ["system:apiserver"]
            verbs: ["get"]
            resources:
              - group: "" # core
                resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
          - level: None
            users: ["cluster-autoscaler"]
            verbs: ["get", "update"]
            namespaces: ["kube-system"]
            resources:
              - group: "" # core
                resources: ["configmaps", "endpoints"]
          # Don't log HPA fetching metrics.
          - level: None
            users:
              - system:kube-controller-manager
              - system:cloud-controller-manager
            verbs: ["get", "list"]
            resources:
              - group: "metrics.k8s.io"

          # Don't log these read-only URLs.
          - level: None
            nonResourceURLs:
              - /healthz*
              - /version
              - /swagger*

          # Don't log events requests because of performance impact.
          - level: None
            resources:
              - group: "" # core
                resources: ["events"]

          # node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
          - level: Request
            users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"
          - level: Request
            userGroups: ["system:nodes"]
            verbs: ["update","patch"]
            resources:
              - group: "" # core
                resources: ["nodes/status", "pods/status"]
            omitStages:
              - "RequestReceived"

          # deletecollection calls can be large, don't log responses for expected namespace deletions
          - level: Request
            users: ["system:serviceaccount:kube-system:namespace-controller"]
            verbs: ["deletecollection"]
            omitStages:
              - "RequestReceived"

          # Secrets, ConfigMaps, TokenRequest and TokenReviews can contain sensitive & binary data,
          # so only log at the Metadata level.
          - level: Metadata
            resources:
              - group: "" # core
                resources: ["secrets", "configmaps", "serviceaccounts/token"]
              - group: authentication.k8s.io
                resources: ["tokenreviews"]
            omitStages:
              - "RequestReceived"
          # Get responses can be large; skip them.
          - level: Request
            verbs: ["get", "list", "watch"]
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "node.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "scheduling.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for known APIs
          - level: RequestResponse
            resources:
              - group: "" # core
              - group: "admissionregistration.k8s.io"
              - group: "apiextensions.k8s.io"
              - group: "apiregistration.k8s.io"
              - group: "apps"
              - group: "authentication.k8s.io"
              - group: "authorization.k8s.io"
              - group: "autoscaling"
              - group: "batch"
              - group: "certificates.k8s.io"
              - group: "extensions"
              - group: "metrics.k8s.io"
              - group: "networking.k8s.io"
              - group: "node.k8s.io"
              - group: "policy"
              - group: "rbac.authorization.k8s.io"
              - group: "scheduling.k8s.io"
              - group: "storage.k8s.io"
            omitStages:
              - "RequestReceived"
          # Default level for all other requests.
          - level: Metadata
            omitStages:
              - "RequestReceived"
      path: /etc/kubernetes/audit-policy/apiserver-audit-policy.yaml
      permissions: "0600"
    - content: |
        #!/bin/bash
        # CAPI does not expose an API to modify KubeProxyConfiguration. For the upstream issue,
        # see https://github.com/kubernetes-sigs/cluster-api/issues/4512.
        #
        # This script is expected to be run before kubeadm itself, using a preKubeadmCommand.
        #
        # To modify the KubeProxyConfiguration, we append it to the kubeadm configuration.
        # The file is expected to be a path that depends on the Bootstrap Type and the Node Type.

        possible_files=()                                       # Bootstrap Type | Node Type
        possible_files+=(/run/kubeadm/kubeadm.yaml)             # cloud-init     | control-plane
        possible_files+=(/run/kubeadm/kubeadm-join-config.yaml) # cloud-init     | node
        possible_files+=(/etc/kubeadm.yml)                      # ignition       | node

        modified_files=()
        for config in "${possible_files[@]}"; do
          if [ -f "$config" ]; then
            cat <<EOF >>"$config"
        ---
        kind: KubeProxyConfiguration
        apiVersion: kubeproxy.config.k8s.io/v1alpha1
        metricsBindAddress: "0.0.0.0:10249"
        EOF
            modified_files+=("$config")
          fi
        done

        printf >&2 "Appended KubeadmProxyConfiguration to: %s\n" "${modified_files[@]}"
      path: /etc/konvoy/append-kube-proxy-configuration.sh
      permissions: "0700"
    - content: |
        [metrics]
          address = "0.0.0.0:1338"
          grpc_histogram = false
      path: /etc/containerd/konvoy-conf.d/konvoy-metrics.toml
      permissions: "0644"
    - content: |
        #!/bin/bash
        set -euo pipefail
        IFS=$'\n\t'

        declare -r TOML_MERGE_IMAGE="ghcr.io/mesosphere/toml-merge:v0.2.0"

        if ! ctr --namespace k8s.io images check "name==${TOML_MERGE_IMAGE}" | grep "${TOML_MERGE_IMAGE}" >/dev/null; then
          ctr --namespace k8s.io images pull "${TOML_MERGE_IMAGE}"
        fi

        cleanup() {
          ctr images unmount "${tmp_ctr_mount_dir}" || true
        }

        trap 'cleanup' EXIT

        readonly tmp_ctr_mount_dir="$(mktemp -d)"

        ctr --namespace k8s.io images mount "${TOML_MERGE_IMAGE}" "${tmp_ctr_mount_dir}"
        "${tmp_ctr_mount_dir}/usr/local/bin/toml-merge" -i --patch-file "/etc/containerd/konvoy-conf.d/*.toml" /etc/containerd/config.toml
      path: /etc/konvoy/containerd-apply-patches.sh
      permissions: "0700"
    - content: |
        #!/bin/bash
        systemctl restart containerd

        if ! command -v crictl; then
          echo "Command crictl is not available, will not wait for Containerd to be running"
          exit
        fi

        SECONDS=0
        until crictl info; do
          if ((SECONDS > 60)); then
            echo "Containerd is not running. Giving up..."
            exit 1
          fi
          echo "Containerd is not running yet. Waiting..."
          sleep 5
        done
      path: /etc/konvoy/restart-containerd-and-wait.sh
      permissions: "0700"
    - content: |
        #!/bin/bash
        set -euo pipefail
        IFS=$'\n\t'

        declare -r CREDENTIAL_PROVIDER_IMAGE="ghcr.io/mesosphere/dynamic-credential-provider:v0.5.3"

        if ! ctr --namespace k8s.io images check "name==${CREDENTIAL_PROVIDER_IMAGE}" | grep "${CREDENTIAL_PROVIDER_IMAGE}" >/dev/null; then
          ctr --namespace k8s.io images pull "${CREDENTIAL_PROVIDER_IMAGE}"
        fi

        cleanup() {
          ctr images unmount "${tmp_ctr_mount_dir}" || true
        }

        trap 'cleanup' EXIT

        readonly tmp_ctr_mount_dir="$(mktemp -d)"

        export CREDENTIAL_PROVIDER_SOURCE_DIR="${tmp_ctr_mount_dir}/opt/image-credential-provider/bin/"
        export CREDENTIAL_PROVIDER_TARGET_DIR="/etc/kubernetes/image-credential-provider/"

        ctr --namespace k8s.io images mount "${CREDENTIAL_PROVIDER_IMAGE}" "${tmp_ctr_mount_dir}"
        "${tmp_ctr_mount_dir}/opt/image-credential-provider/bin/dynamic-credential-provider" install
      path: /etc/konvoy/install-kubelet-credential-providers.sh
      permissions: "0700"
    - contentFrom:
        secret:
          key: value
          name: {{ .Values.cluster.name }}-etcd-encryption-config
      owner: root:root
      path: /etc/kubernetes/pki/encryption-config.yaml
      permissions: "0640"
    format: cloud-config
    initConfiguration:
      localAPIEndpoint: {}
      nodeRegistration:
{{- if .Values.cluster.singleNode }}
        taints: []
{{- end }}
        criSocket: unix:///run/containerd/containerd.sock
        ignorePreflightErrors:
        - SystemVerification
        imagePullPolicy: IfNotPresent
        kubeletExtraArgs:
          cloud-provider: ""
          provider-id: '{{ .ProviderID }}'
    joinConfiguration:
      discovery: {}
      nodeRegistration:
{{- if .Values.cluster.singleNode }}
        taints: []
{{- end }}
        criSocket: unix:///run/containerd/containerd.sock
        ignorePreflightErrors:
        - SystemVerification
        imagePullPolicy: IfNotPresent
        kubeletExtraArgs:
          cloud-provider: ""
          provider-id: '{{ .ProviderID }}'
    postKubeadmCommands:
    - /etc/konvoy/configure-kube-vip.sh use-admin.conf
    preKubeadmCommands:
    - /etc/konvoy/append-kube-proxy-configuration.sh
    - /etc/konvoy/install-kubelet-credential-providers.sh
    - /etc/konvoy/containerd-apply-patches.sh
    - systemctl daemon-reload
    - /etc/konvoy/restart-containerd-and-wait.sh
    - /etc/konvoy/configure-kube-vip.sh use-super-admin.conf
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
      kind: PreprovisionedMachineTemplate
      name: {{ .Values.cluster.name }}-control-plane
      namespace: {{ .Values.cluster.namespace }}
    metadata: {}
  replicas: {{ .Values.cluster.controlPlane.replicas }}
  rolloutBefore:
    certificatesExpiryDays: 180 
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  version: v1.34.3 
---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.cluster.controlPlane.endpointHost | quote }}
    port: {{ .Values.cluster.controlPlaneEndpoint.port }}
  virtualIP:
    interface: {{ .Values.cluster.controlPlane.virtualIPInterface }}
---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  template:
    spec:
      inventoryRef:
        name: {{ .Values.cluster.name }}-control-plane
        namespace: {{ .Values.cluster.namespace }}
---
apiVersion: infrastructure.cluster.konvoy.d2iq.io/v1alpha1
kind: PreprovisionedInventory
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-control-plane
  namespace: {{ .Values.cluster.namespace }}
spec:
  hosts:
{{- range .Values.cluster.controlPlane.hosts }}
  - address: {{ .address | quote }}
{{- end }}
  sshConfig:
    port: 22
    privateKeyRef:
      name: {{ .Values.cluster.name }}-ssh-key
      namespace: {{ .Values.cluster.namespace }}
    user: {{ .Values.cluster.ssh.user }}
