apiVersion: v1
data:
  value: a2luZDogRW5jcnlwdGlvbkNvbmZpZwphcGlWZXJzaW9uOiB2MQpyZXNvdXJjZXM6CiAgLSByZXNvdXJjZXM6CiAgICAgIC0gc2VjcmV0cwogICAgICAtIGNvbmZpZ21hcHMKICAgIHByb3ZpZGVyczoKICAgICAgLSBhZXNjYmM6CiAgICAgICAgICBrZXlzOgogICAgICAgICAgICAtIG5hbWU6IGtleQogICAgICAgICAgICAgIHNlY3JldDogY3JLS3E3aFFaQTNwak5LZ20yV0dKNUxVTlRKUzJpVmgyZnZaRzA1endwWT0KICAgICAgLSBpZGVudGl0eToge30=
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-etcd-encryption-config
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
---
apiVersion: v1
data:
  ssh-privatekey: {{ .Values.cluster.ssh.privateKeyBase64 | quote }}
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-ssh-key
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
---
apiVersion: v1
data:
  mirror: {{ include "nkp-2.17.1.containerdMirrorConfig" . | b64enc }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-control-plane-containerd-configuration
  namespace: {{ .Values.cluster.namespace }}
type: Opaque
---
apiVersion: v1
data:
  mirror: {{ include "nkp-2.17.1.containerdMirrorConfig" . | b64enc }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.cluster.name }}
    clusterctl.cluster.x-k8s.io/move: ""
  name: {{ .Values.cluster.name }}-md-0-containerd-configuration
  namespace: {{ .Values.cluster.namespace }}
type: Opaque